# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Windows/Users/Robin/Desktop/Shared/Cours/M2/S9/Projet/BinPacking3DM2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Windows/Users/Robin/Desktop/Shared/Cours/M2/S9/Projet/BinPacking3DM2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Windows/Users/Robin/Desktop/Shared/Cours/M2/S9/Projet/BinPacking3DM2/CMakeFiles /Windows/Users/Robin/Desktop/Shared/Cours/M2/S9/Projet/BinPacking3DM2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Windows/Users/Robin/Desktop/Shared/Cours/M2/S9/Projet/BinPacking3DM2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BinPacking3DM2

# Build rule for target.
BinPacking3DM2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BinPacking3DM2
.PHONY : BinPacking3DM2

# fast build rule for target.
BinPacking3DM2/fast:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/build
.PHONY : BinPacking3DM2/fast

Src/2D/Algorithm.o: Src/2D/Algorithm.cpp.o

.PHONY : Src/2D/Algorithm.o

# target to build an object file
Src/2D/Algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Algorithm.cpp.o
.PHONY : Src/2D/Algorithm.cpp.o

Src/2D/Algorithm.i: Src/2D/Algorithm.cpp.i

.PHONY : Src/2D/Algorithm.i

# target to preprocess a source file
Src/2D/Algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Algorithm.cpp.i
.PHONY : Src/2D/Algorithm.cpp.i

Src/2D/Algorithm.s: Src/2D/Algorithm.cpp.s

.PHONY : Src/2D/Algorithm.s

# target to generate assembly for a file
Src/2D/Algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Algorithm.cpp.s
.PHONY : Src/2D/Algorithm.cpp.s

Src/2D/ArbreBinaire.o: Src/2D/ArbreBinaire.cpp.o

.PHONY : Src/2D/ArbreBinaire.o

# target to build an object file
Src/2D/ArbreBinaire.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/ArbreBinaire.cpp.o
.PHONY : Src/2D/ArbreBinaire.cpp.o

Src/2D/ArbreBinaire.i: Src/2D/ArbreBinaire.cpp.i

.PHONY : Src/2D/ArbreBinaire.i

# target to preprocess a source file
Src/2D/ArbreBinaire.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/ArbreBinaire.cpp.i
.PHONY : Src/2D/ArbreBinaire.cpp.i

Src/2D/ArbreBinaire.s: Src/2D/ArbreBinaire.cpp.s

.PHONY : Src/2D/ArbreBinaire.s

# target to generate assembly for a file
Src/2D/ArbreBinaire.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/ArbreBinaire.cpp.s
.PHONY : Src/2D/ArbreBinaire.cpp.s

Src/2D/CSVReader.o: Src/2D/CSVReader.cpp.o

.PHONY : Src/2D/CSVReader.o

# target to build an object file
Src/2D/CSVReader.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/CSVReader.cpp.o
.PHONY : Src/2D/CSVReader.cpp.o

Src/2D/CSVReader.i: Src/2D/CSVReader.cpp.i

.PHONY : Src/2D/CSVReader.i

# target to preprocess a source file
Src/2D/CSVReader.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/CSVReader.cpp.i
.PHONY : Src/2D/CSVReader.cpp.i

Src/2D/CSVReader.s: Src/2D/CSVReader.cpp.s

.PHONY : Src/2D/CSVReader.s

# target to generate assembly for a file
Src/2D/CSVReader.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/CSVReader.cpp.s
.PHONY : Src/2D/CSVReader.cpp.s

Src/2D/Composant.o: Src/2D/Composant.cpp.o

.PHONY : Src/2D/Composant.o

# target to build an object file
Src/2D/Composant.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Composant.cpp.o
.PHONY : Src/2D/Composant.cpp.o

Src/2D/Composant.i: Src/2D/Composant.cpp.i

.PHONY : Src/2D/Composant.i

# target to preprocess a source file
Src/2D/Composant.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Composant.cpp.i
.PHONY : Src/2D/Composant.cpp.i

Src/2D/Composant.s: Src/2D/Composant.cpp.s

.PHONY : Src/2D/Composant.s

# target to generate assembly for a file
Src/2D/Composant.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Composant.cpp.s
.PHONY : Src/2D/Composant.cpp.s

Src/2D/Conteneur.o: Src/2D/Conteneur.cpp.o

.PHONY : Src/2D/Conteneur.o

# target to build an object file
Src/2D/Conteneur.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Conteneur.cpp.o
.PHONY : Src/2D/Conteneur.cpp.o

Src/2D/Conteneur.i: Src/2D/Conteneur.cpp.i

.PHONY : Src/2D/Conteneur.i

# target to preprocess a source file
Src/2D/Conteneur.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Conteneur.cpp.i
.PHONY : Src/2D/Conteneur.cpp.i

Src/2D/Conteneur.s: Src/2D/Conteneur.cpp.s

.PHONY : Src/2D/Conteneur.s

# target to generate assembly for a file
Src/2D/Conteneur.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Conteneur.cpp.s
.PHONY : Src/2D/Conteneur.cpp.s

Src/2D/Position2D.o: Src/2D/Position2D.cpp.o

.PHONY : Src/2D/Position2D.o

# target to build an object file
Src/2D/Position2D.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Position2D.cpp.o
.PHONY : Src/2D/Position2D.cpp.o

Src/2D/Position2D.i: Src/2D/Position2D.cpp.i

.PHONY : Src/2D/Position2D.i

# target to preprocess a source file
Src/2D/Position2D.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Position2D.cpp.i
.PHONY : Src/2D/Position2D.cpp.i

Src/2D/Position2D.s: Src/2D/Position2D.cpp.s

.PHONY : Src/2D/Position2D.s

# target to generate assembly for a file
Src/2D/Position2D.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Position2D.cpp.s
.PHONY : Src/2D/Position2D.cpp.s

Src/2D/Rectangle.o: Src/2D/Rectangle.cpp.o

.PHONY : Src/2D/Rectangle.o

# target to build an object file
Src/2D/Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Rectangle.cpp.o
.PHONY : Src/2D/Rectangle.cpp.o

Src/2D/Rectangle.i: Src/2D/Rectangle.cpp.i

.PHONY : Src/2D/Rectangle.i

# target to preprocess a source file
Src/2D/Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Rectangle.cpp.i
.PHONY : Src/2D/Rectangle.cpp.i

Src/2D/Rectangle.s: Src/2D/Rectangle.cpp.s

.PHONY : Src/2D/Rectangle.s

# target to generate assembly for a file
Src/2D/Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/2D/Rectangle.cpp.s
.PHONY : Src/2D/Rectangle.cpp.s

Src/3D/Position3D.o: Src/3D/Position3D.cpp.o

.PHONY : Src/3D/Position3D.o

# target to build an object file
Src/3D/Position3D.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/3D/Position3D.cpp.o
.PHONY : Src/3D/Position3D.cpp.o

Src/3D/Position3D.i: Src/3D/Position3D.cpp.i

.PHONY : Src/3D/Position3D.i

# target to preprocess a source file
Src/3D/Position3D.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/3D/Position3D.cpp.i
.PHONY : Src/3D/Position3D.cpp.i

Src/3D/Position3D.s: Src/3D/Position3D.cpp.s

.PHONY : Src/3D/Position3D.s

# target to generate assembly for a file
Src/3D/Position3D.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/3D/Position3D.cpp.s
.PHONY : Src/3D/Position3D.cpp.s

Src/main.o: Src/main.cpp.o

.PHONY : Src/main.o

# target to build an object file
Src/main.cpp.o:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/main.cpp.o
.PHONY : Src/main.cpp.o

Src/main.i: Src/main.cpp.i

.PHONY : Src/main.i

# target to preprocess a source file
Src/main.cpp.i:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/main.cpp.i
.PHONY : Src/main.cpp.i

Src/main.s: Src/main.cpp.s

.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.cpp.s:
	$(MAKE) -f CMakeFiles/BinPacking3DM2.dir/build.make CMakeFiles/BinPacking3DM2.dir/Src/main.cpp.s
.PHONY : Src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... BinPacking3DM2"
	@echo "... edit_cache"
	@echo "... Src/2D/Algorithm.o"
	@echo "... Src/2D/Algorithm.i"
	@echo "... Src/2D/Algorithm.s"
	@echo "... Src/2D/ArbreBinaire.o"
	@echo "... Src/2D/ArbreBinaire.i"
	@echo "... Src/2D/ArbreBinaire.s"
	@echo "... Src/2D/CSVReader.o"
	@echo "... Src/2D/CSVReader.i"
	@echo "... Src/2D/CSVReader.s"
	@echo "... Src/2D/Composant.o"
	@echo "... Src/2D/Composant.i"
	@echo "... Src/2D/Composant.s"
	@echo "... Src/2D/Conteneur.o"
	@echo "... Src/2D/Conteneur.i"
	@echo "... Src/2D/Conteneur.s"
	@echo "... Src/2D/Position2D.o"
	@echo "... Src/2D/Position2D.i"
	@echo "... Src/2D/Position2D.s"
	@echo "... Src/2D/Rectangle.o"
	@echo "... Src/2D/Rectangle.i"
	@echo "... Src/2D/Rectangle.s"
	@echo "... Src/3D/Position3D.o"
	@echo "... Src/3D/Position3D.i"
	@echo "... Src/3D/Position3D.s"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

